/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class math */

#ifndef _Included_math
#define _Included_math
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     math
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lbrant_jni_MathJNI_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
